config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :posts
  devise_for :users
  get 'bandposts/index'
  root to: "bandposts#index"
  resources :bandposts do
    collection do
      get 'search'
      get 'select_category_index'
    end
  end
  resources :soloposts do
    collection do
      get 'search'
      get 'select_category_index'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '地域' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }

  ]

  include ActiveHash::Associations
  has_many :bandposts
  has_many :soloposts


end

app/models/bandpost.rb
class Bandpost < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one_attached :video

  def self.search(search)
    if search != ""
      Bandpost.where('bandname LIKE(?)', "%#{search}%")
    else
      Bandpost.all
    end
  end


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :area
  belongs_to :musical_instrument

  validates :bandname, :introduction, presence: true
  validates :genre_id, :area_id, :musical_instrument_id, numericality: { other_than: 1 } 
  validates :image, :video, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ジャンル' },
    { id: 2, name: 'ロック' },
    { id: 3, name: 'Jポップ' },
    { id: 4, name: 'ファンク' },
    { id: 5, name: 'パンク' },
    { id: 6, name: 'メロコア' },
    { id: 7, name: 'メタル' },
    { id: 8, name: 'ラウド' },
    { id: 9, name: 'スカ' },
    { id: 10, name: 'ブルース' },
    { id: 11, name: 'オルタナティブ' },
    { id: 12, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :bandposts
  has_many :soloposts

end

app/models/musical_instrument.rb
class MusicalInstrument < ActiveHash::Base
  self.data = [
    { id: 1, name: '楽器' },
    { id: 2, name: 'ボーカル' },
    { id: 3, name: 'ギター' },
    { id: 4, name: 'ベース' },
    { id: 5, name: 'ドラム' },
    { id: 6, name: 'キーボード' },
    { id: 7, name: '金管楽器' },
    { id: 8, name: '木管楽器' },
    { id: 9, name: 'その他' },
  ]
  
  include ActiveHash::Associations
  has_many :bandposts
  has_many :soloposts

end

app/models/solopost.rb
class Solopost < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one_attached :video

  def self.search(search)
    if search != ""
      Solopost.where('nickname LIKE(?)', "%#{search}%")
    else
      Solopost.all
    end
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :area
  belongs_to :musical_instrument

  validates :nickname, :introduction, presence: true
  validates :genre_id, :area_id, :musical_instrument_id, numericality: { other_than: 1 } 
  validates :image, :video, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bandposts
  has_many :soloposts

  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i, message: 'Include both letters and numbers' } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end

end

app/controllers/bandposts_controller.rb
class BandpostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_bandpost, only: [:show, :edit, :update, :destroy]

  def index
    @bandposts = Bandpost.all.order("created_at DESC")
  end


  def new
    @bandpost = Bandpost.new
  end

  def create
    @bandpost = Bandpost.new(bandpost_params)

    if @bandpost.save
      redirect_to root_path
    else
      render :new
    end

  end

  def show
  end

  def edit
  end

  def update
    if @bandpost.update(bandpost_params)
      redirect_to bandpost_path
    else
      render :edit
    end
  end

  def destroy
    @bandpost.destroy
    redirect_to root_path
  end

  def search
    @bandposts = Bandpost.search(params[:keyword]) 
  end

  private
  def bandpost_params
    params.require(:bandpost).permit(:bandname, :introduction, :genre_id, :musical_instrument_id, :area_id, :history, :sns_account, :image, :video ).merge(user_id:current_user.id)
  end

  def set_bandpost
    @bandpost = Bandpost.find(params[:id])
  end

end

app/controllers/soloposts_controller.rb
class SolopostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_solopost, only: [:show, :edit, :update, :destroy]

  def index
    @soloposts = Solopost.all.order("created_at DESC")
  end

  def new
    @solopost = Solopost.new
  end

  def create
    @solopost = Solopost.new(solopost_params)

    if @solopost.save
      redirect_to soloposts_path
    else
      render :new
    end

  end

  def show
  end

  def edit
  end

  def update
    if @solopost.update(solopost_params)
      redirect_to solopost_path
    else
      render :edit
    end
  end

  def destroy
    @solopost.destroy
    redirect_to solopost_path
  end

  def search
    @soloposts = Solopost.search(params[:keyword])
  end

  private
  def solopost_params
    params.require(:solopost).permit(:nickname, :introduction, :genre_id, :musical_instrument_id, :area_id, :favorite_band, :history, :sns_account, :image, :video ).merge(user_id:current_user.id)
  end

  def set_solopost
    @solopost = Solopost.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @bandposts = current_user.bandposts
    @soloposts = current_user.soloposts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bandposts_helper.rb
module BandpostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/soloposts_helper.rb
module SolopostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bandposts/_bandpost.html.erb
<% @bandposts.each do |bandpost| %>
    <li class='list'>
        <%= link_to bandpost_path(bandpost.id) do %>
          <div class='item-img-content'>
            <%= image_tag bandpost.image.variant(resize: '500x500'), class: "item-img" if bandpost.image.attached? %>
          </div>
          <div class='band-info'>
            <h3 class='band-name'>
              <%= bandpost.bandname %>
            </h3>
            <div class='band-info2'>
              <span><%= bandpost.genre.name %><span>
              <span><%= bandpost.musical_instrument.name %><span>
              <span><%= bandpost.area.name %><span>
            </div>
          </div>
        <% end %>
    </li>
  <% end %>

app/views/bandposts/edit.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">バンドの情報を入力</h2>
    <%= form_with(model: @bandpost, local: true) do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>
    
    <%# バンド画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        バンド画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /バンド画像 %>
    <%# バンド映像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        バンド映像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :video, id:"item-image" %>
      </div>
    </div>
    <%# /バンド映像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        バンド名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :bandname, class:"items-text", id:"item-name" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          バンドの自己紹介
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# バンドの詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">バンドの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          募集楽器
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:musical_instrument_id, MusicalInstrument.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          活動地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          活動歴
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :history, class:"items-text", id:"item-name" %>
        <div class="weight-bold-text">
          SNSアカウント
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :sns_account, class:"items-text", id:"item-name" %>
      </div>
    </div>
    <%# /バンドの詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

app/views/bandposts/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <div class='search-bar-contents'>
    <%= form_with(url: search_bandposts_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "バンド名を検索する", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
      <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li class="genre-list" id="genre-list">ジャンル
      </li>
      <li><%= link_to '地域', "#", class: "area-list" %></li>
      <li><%= link_to '楽器', "#", class: "musical-instrument-list" %></li>
    </ul>
    <ul class='lists-right'>
      <li><%= link_to 'バンド投稿', new_bandpost_path, class: "band-post-btn"%></li>
      <li><%= link_to 'ソロプレイヤー投稿一覧', soloposts_path, class: "solo-index" %></li>
    </ul>
  </div>
  
</div>
  <%# バンド一覧 %>
  <div class='item-contents'>
    <h2 class='title'>バンド一覧</h2>
    <ul class='item-lists'>
<%if @bandposts.present? %>
  <% @bandposts.each do |bandpost| %>
    <li class='list'>
        <%= link_to bandpost_path(bandpost.id) do %>
          <div class='item-img-content'>
            <%= image_tag bandpost.image.variant(resize: '500x500'), class: "item-img" if bandpost.image.attached? %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= bandpost.bandname %>
            </h3>
            <div class='band-info2'>
              <span><%= bandpost.genre.name %><span>
              <span><%= bandpost.musical_instrument.name %><span>
              <span><%= bandpost.area.name %><span>
            </div>
          </div>
        <% end %>
    </li>
  <% end %>
<% else %>
      <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "test-sample.jpg", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              バンドを投稿してね！
            </h3>
            <span><%= "ジャンル" %><span>
            <span><%= "募集している楽器" %><span>
            <span><%= "活動地域" %><span>
          </div>
          <% end %>
      </li>
  
<% end %>
  </div>
  <%# /バンド一覧 %>

app/views/bandposts/new.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">バンドの情報を入力</h2>
    <%= form_with model: @bandpost, local: true do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>
    

    <%# バンド画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        バンド画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /バンド画像 %>
    <%# バンド映像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        バンド映像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :video, id:"item-image" %>
      </div>
    </div>
    <%# /バンド映像 %>
    <%# バンドの詳細 %>
    <div class="new-items">
      <div class="weight-bold-text">
        バンド名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :bandname, class:"items-text", id:"item-name" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          バンドの自己紹介
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">バンドの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre-category"}) %>
        <div class="weight-bold-text">
          募集楽器
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:musical_instrument_id, MusicalInstrument.all, :id, :name, {}, {class:"select-box", id:"musical-instrument-category"}) %>
        <div class="weight-bold-text">
          活動地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"area-category"}) %>
        <div class="weight-bold-text">
          活動歴
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :history, class:"items-text", id:"item-name" %>
        <div class="weight-bold-text">
          SNSアカウント
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :sns_account, class:"items-text", id:"item-name" %>
      </div>
    </div>
    <%# /バンドの詳細 %>

    
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

app/views/bandposts/search.html.erb
<%= render "shared/header" %>

<%= form_with(url: search_bandposts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "バンド名を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'ジャンル', "#", class: "genre-list" %></li>
      <li><%= link_to '地域', "#", class: "area-list" %></li>
      <li><%= link_to '楽器', "#", class: "musical-instrument-list" %></li>
    </ul>
    <ul class='lists-right'>
      <li><%= link_to 'バンド投稿', new_bandpost_path, class: "band-post-btn"%></li>
      <li><%= link_to 'ソロ一覧', soloposts_path, class: "solo-index" %></li>
    </ul>
 </div>
</div>

<div class="list">
  <% @bandposts.each do |bandpost| %>
    <%= render partial: "bandpost", locals: { bandpost: bandpost } %>
  <% end %>
</div>

app/views/bandposts/show.html.erb
<%= render "shared/header" %>

<%# バンドの概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @bandpost.bandname %>
    </h2>
    <div class="item-explain-box">
      <span><%= @bandpost.introduction %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ジャンル</th>
          <td class="detail-value"><%= @bandpost.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-item">募集楽器</th>
          <td class="detail-value"><%= @bandpost.musical_instrument.name %></td>
        </tr>
        <tr>
          <th class="detail-item">活動地域</th>
          <td class="detail-value"><%= @bandpost.area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">活動歴</th>
          <td class="detail-value"><%= @bandpost.history %></td>
        </tr>
        <tr>
          <th class="detail-item">SNSアカウント</th>
          <td class="detail-value"><%= @bandpost.sns_account %></td>
        </tr>
      </tbody>
    </table>
    <div class="item-img-content">
      <%= image_tag @bandpost.image.variant(resize: '500x500') ,class:"item-box-img" %>  
    </div>
    <% if @bandpost.video.attached? %>
    <div class="item-img-content">
      <video src="<%= rails_blob_path(@bandpost.video) %>" type="video/mp4" controls ></video>
      
    </div>
    <% end %>
      <% if current_user.id == @bandpost.user_id %>
        <%= link_to "バンド情報の編集", edit_bandpost_path(@bandpost.id), method: :get, class: "item-green-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", bandpost_path(@bandpost.id), method: :delete, class:"item-destroy" %>
      <% end %>
  </div>
  <%# /商品の概要 %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BandApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.video %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to @post.video_url.to_s do %>
   <%= video_tag(@post.video.to_s) %>
  <% end %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/soloposts/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='search-bar-contents'>
    
    <%= form_with(url: search_soloposts_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "ニックネームを検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>

  </div>

<div class='nav'>
    <ul class='lists-left'>
      <li class="genre-list" id="genre-list">ジャンル
      </li>
      <li><%= link_to '地域', "#", class: "area-list" %></li>
      <li><%= link_to '楽器', "#", class: "musical-instrument-list" %></li>
    </ul>
    <ul class='lists-right'>
      <li><%= link_to 'ソロ投稿', new_solopost_path, class: "band-post-btn"%></li>
      <li><%= link_to 'バンド投稿一覧へ', bandposts_path, class: "solo-index" %></li>
    </ul>
 </div>
</div>
  <%# ソロ一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ソロプレイヤー投稿一覧</h2>
    <ul class='item-lists'>
<%if @soloposts.present? %>
  <% @soloposts.each do |solopost| %>
    <li class='list'>
        <%= link_to solopost_path(solopost.id) do %>
          
            <div class='item-img-content'>
            <%= image_tag solopost.image.variant(resize: '500x500'), class: "item-img" if solopost.image.attached? %>
            </div>
         
          <div class='band-info'>
            <h3 class='band-name'>
              <%= solopost.nickname %>
            </h3>
            <div class='band-info2'>
              <span><%= solopost.genre.name %><span>
              <span><%= solopost.musical_instrument.name %><span>
              <span><%= solopost.area.name %><span>
            </div>
          </div>
        <% end %>
    </li>
  <% end %>
<% else %>
      <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "test-sample.jpg", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              ソロ情報を投稿してね！
            </h3>
            <span><%= "ジャンル" %><span>
            <span><%= "担当している楽器" %><span>
            <span><%= "活動地域" %><span>
          </div>
          <% end %>
      </li>
  
<% end %>
  </div>
  <%# /バンド一覧 %>

app/views/soloposts/search.html.erb
<%= render "shared/header" %>
<%= form_with(url: search_soloposts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "ニックネームを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'ジャンル', "#", class: "genre-list" %></li>
      <li><%= link_to '地域', "#", class: "area-list" %></li>
      <li><%= link_to '楽器', "#", class: "musical-instrument-list" %></li>
    </ul>
    <ul class='lists-right'>
      <li><%= link_to 'ソロ投稿', new_solopost_path, class: "band-post-btn"%></li>
      <li><%= link_to 'バンド一覧へ', bandposts_path, class: "solo-index" %></li>
    </ul>
 </div>
</div>

<div class="list">
  <% @soloposts.each do |solopost| %>
    <%= render partial: "solopost", locals: { solopost: solopost } %>
  <% end %>
</div>

app/views/soloposts/show.html.erb
<%= render "shared/header" %>

<%# バンドの概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @solopost.nickname %>
    </h2>
    <div class="item-explain-box">
      <span><%= @solopost.introduction %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ジャンル</th>
          <td class="detail-value"><%= @solopost.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-item">担当楽器</th>
          <td class="detail-value"><%= @solopost.musical_instrument.name %></td>
        </tr>
        <tr>
          <th class="detail-item">活動地域</th>
          <td class="detail-value"><%= @solopost.area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">好きなバンド</th>
          <td class="detail-value"><%= @solopost.favorite_band %></td>
        </tr>
        <tr>
          <th class="detail-item">活動歴</th>
          <td class="detail-value"><%= @solopost.history %></td>
        </tr>
        <tr>
          <th class="detail-item">SNSアカウント</th>
          <td class="detail-value"><%= @solopost.sns_account %></td>
        </tr>
      </tbody>
    </table>

    <div class="item-img-content">
      <%= image_tag @solopost.image.variant(resize: '500x500') ,class:"item-box-img" %>  
    </div>
    <% if @solopost.video.attached? %>
    <div class="item-img-content">
      <video src="<%= rails_blob_path(@solopost.video) %>" type="video/mp4" controls ></video>
      
    </div>
    <% end %>
      <% if current_user.id == @solopost.user_id %>
        <%= link_to "ソロプレイヤー情報の編集", edit_solopost_path(@solopost.id), method: :get, class: "item-green-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", solopost_path(@solopost.id), method: :delete, class:"item-destroy" %>
      <% end %>
  </div>
  <%# /商品の概要 %>